### ISSUE TITLE
All architectures binary must be provided.

### ISSUE THREAD

**Issue by xplatsolutions** [NAXAM/stripe-ios-binding#1]
Thank you for your work :-)

I guess you didn't try it with the Simulator, but how are you handling the different architectures?
The solution is to build a fat binary for all architectures, see in my repo here, https://github.com/xplatsolutions/Stripe-Xamarin-iOS-Bindings/tree/master/FromSource.

The ideal would be to have one library for simulator and one for device and change using a build script or with your CI-CD platform.

Let me know how would you prefer to tackle this.

P.S. I think it's better to build two framework and not carry the static library binary only because I noticed resources will be missing, I will add the frameworks in my repo if you want or let me know how we can connect, my email is taskos.george@gmail.com :-)

**Comment by tuyen-vuduc** [comment]
You are right!

The provided framework from the pod isn't that `fat` (I built the binding using Sharpie POD).

We will need to build a really `fat` framework from source.

You could reach me at tuyen@naxam.net.

**Comment by kanvuduc** [comment]
Commit e103934519bfbd4b855d678cce1b7f0bac3dc548 closes #1

**Comment by tuyen-vuduc** [comment]
Commit 026a36643faed59874b66d5f3c93d8cbef4c20fa
