### ISSUE TITLE
STPSourceProtocol.StripeID is throwing a null reference exception

### ISSUE THREAD

**Issue by xplatsolutions** [NAXAM/stripe-ios-binding#2]
I had the same issue with this, let's see if we can fix it.

In implementing `STPBackendAPIAdapter.SelectDefaultCustomerSource` and accessing the parameter `STPSourceProtocol source` for the property StripeID throws a NullReferenceException, if you debug at that point you can see an STPCard with the values but accessing the property will throw. Cast is also not possible.

I have worked around the problem using `source.ValueForKeyPath(new NSString("stripeID"));` and worked.

Let me know if you have any ideas.

**Comment by tuyen-vuduc** [comment]
b767d1a1f53b28562da82063103c4985854c5a9d closes #2
