### ISSUE TITLE
Issue with generated protocol property (STPSourceProtocol)

### ISSUE THREAD

**Issue by xplatsolutions** [NAXAM/stripe-ios-binding#3]
Add to the demo the below code to get an exception, not sure what is needed but it can't cast STPCard to STPSourceProtocol.

```
public void PaymentContext(STPPaymentContext paymentContext, STPPaymentResult paymentResult, STPErrorBlock completion)
{
    // Specified cast is not valid
    var stripeID = paymentResult.Source.StripeID;
}
```

Let me know if you have any idea.

**Comment by tuyen-vuduc** [comment]
:). This kind of issues is only reveal when in use. It's because the generated code for protocol isn't always correct. However it's very easy to fix.
