### ISSUE TITLE
STPSource is not inherited from ISTPAPIResponseDecodable and ISTPSourceProtocol

### ISSUE THREAD

**Issue by kyhosy** [NAXAM/stripe-ios-binding#6]
Hi NAXAM.
I'm Ky. Mobile developer of mobile Xamarin. I had project using Stride payment sdk, so i use package Naxam.Stripe.iOS 11.3.0.
And i found that STPSource is not inherited from ISTPAPIResponseDecodable and ISTPSourceProtocol on dll.
It means: STPSource can't found property StripeID ( ISTPSourceProtocol has StripeID).
It's very serious, because we will can't access to some properties or has a correct type from STPSource to make a charge payment with backend-api.
So i had investigated in the project binding find something:
Code on Apidefinition.cs

> [BaseType(typeof(NSObject))]
>     [DisableDefaultCtor]
>     interface STPSource : _**ISTPAPIResponseDecodable, ISTPSourceProtocol**_
...

I have solution for the issue. 

> [BaseType(typeof(NSObject))]
>     [DisableDefaultCtor]
>     interface STPSource : **_STPAPIResponseDecodable, STPSourceProtocol_**
...

So i hope it will make the binding of stripe is better.

**Comment by tuyen-vuduc** [comment]
Hi Ky,

Thank you very much for finding the issue.

Plz try to make the change and verify at your side then submit a pull request. 

I am very happy to merge to the main code base and publish the update.

Cheers.

**Comment by tuyen-vuduc** [comment]
Commit 217def6eda92c434d0bea0304b7d8da928841e1f
