### ISSUE TITLE
Running demo app

### ISSUE THREAD

**Issue by dinonovak** [NAXAM/stripe-ios-binding#8]
Hi,
I am trying to run demo app, and with test PublishableKey

when card number is entered and verification is started I am getting the following error: 

Failed to compute the token reference for the type 'StripeSdk.ISTPSourceProtocol, Naxam.Stripe.iOS, Version=13.0.2.0, Culture=neutral, PublicKeyToken=null' because the assembly couldn't be found in the list of registered assemblies.

**Comment by tuyen-vuduc** [comment]
Duplicate #9.
